### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by FancyRedCat** [flash62au/WiTcontroller#10]
Hi,

I build my own WiTcontroller and loaded the firmware. Thanks for your work it runs so far great.
But I stumbled upon the sentences "_I would appreciate any assistance to improve these translations. If you are interested, please contact me directly for instructions._" I looked into the German translation file and you're right, Google is bad at translating railway terms. How can I support this project?

Best regards

**Comment by flash62au** [comment]
Hi,
the main work needed is with the 'Deutsche Übersetzungen.txt' text file.  
There is limited space on the oLED screen so a) many German words are longer than English words so would benefit from being abbreviated, and b) I had abbreviated many of the English words to start with, so Google did not translate them, or translated them badly.

Beyond that, the whole README.md file could be translated if you were interested.

If you are interested, it would be easier to communicate on the DCC-EX discord server https://discord.gg/8ghsjsBup8
My handle there is 'flash62au (Peter A)'
