### ISSUE TITLE
Description still says "Bluetooth" even though it's "WiFi"

### ISSUE THREAD

**Issue by newHeiko** [flash62au/WiTcontroller#3]
Hi Peter,

your repo description says "Bluetooth" when in fact it's a "WiFi" (isn't it?):
![image](https://github.com/flash62au/WiTcontroller/assets/35038740/d5c1c5ce-3ec1-48ec-84f6-0647e2706ab4)
![image](https://github.com/flash62au/WiTcontroller/assets/35038740/a5451938-51c5-43f9-9140-3c01d8f425f3)

Not a big deal, just when I can't remember the exact repo name and google, I tend to skip over the correct link a couple of times because of that.

Heiko

P.S: Thanks for publishing your project. It's great to see kindred spirits :)

**Comment by flash62au** [comment]
Thanks.
I shall fix shortly.


Peter
