### ISSUE TITLE
Disconnects and resets the DCC EX station

### ISSUE THREAD

**Issue by 2wheelsnz** [flash62au/WiTcontroller#4]
I have just built this controller and loaded the code v 1.33  
WiTcontroller connects to WiFi and I can connect to my DCC EX (Developer version 5.2.17) but within 30 seconds WiTcontroller disconnects.  At the same time, IF I have Engine Driver running on my tablet, that also gets disconnected at the same time.  I have been running this version of DCC EX and Engine Driver the last few weeks and no problem.  
It's only since adding the WiTcontroller and within 30 seconds of it connecting do I see these disconnects.
If I start the controller and leave it connected to the WiFi but NOT connected to DCC EX, it just sits at the screen for the witServer IP:Port

I tried to find version 1.06 which is mentioned on the GitHub page that is stable, but I don't seem to be able to find it.
I am more than happy to assist in testing wherever possible.
I am running an Ethernet shield on the DCC EX, not a WiFi shield.  Engine Driver on the tablet has been working great with this setup.
The board for the WiTcontroller is a WEMOS Lite (AliExpress).
Any assistance would be great.
Kind regards
Barry.

**Comment by flash62au** [comment]
Sorry, I completely missed your message here.
Please contact me on Discord and I will work with you.
https://discord.gg/3mxXmrCh

flash62au (Peter A)

**Comment by 2wheelsnz** [comment]
My bad,  I reached out on Discord and you helped solve the issue.  I did say I would come back to close this ticket but I forgot.  Sorry about that.  An update at this time is that it has been working flawlessly since the initial issue.  So once again, many thanks for your help.  Kind regards  Barry.
